### ISSUE TITLE
BanStick needs to shade in ipaddress 2.0.2

### ISSUE THREAD

**Issue by Diet-Cola** [CivMC/Civ#187]
Will prevent: 
```
[01:31:48 ERROR]: Error occurred while enabling BanStick v2.0.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: inet/ipaddr/IPAddressStringException
        at com.programmerdan.minecraft.banstick.handler.BanStickCommandHandler.registerCommands(BanStickCommandHandler.java:32) ~[banstick-2.0.0-SNAPSHOT.jar:?]
        at com.programmerdan.minecraft.banstick.handler.BanStickCommandHandler.<init>(BanStickCommandHandler.java:28) ~[banstick-2.0.0-SNAPSHOT.jar:?]
        at com.programmerdan.minecraft.banstick.BanStick.registerCommandHandler(BanStick.java:122) ~[banstick-2.0.0-SNAPSHOT.jar:?]
        at com.programmerdan.minecraft.banstick.BanStick.onEnable(BanStick.java:52) ~[banstick-2.0.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.jar:git-Paper-"74fd151"]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.jar:git-Paper-"74fd151"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.jar:git-Paper-"74fd151"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.jar:git-Paper-"74fd151"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-"74fd151"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-"74fd151"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-"74fd151"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: inet.ipaddr.IPAddressStringException
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 15 more
```
on plugin load

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
