### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by wingzero54** [CivMC/Civ#69]
[09:14:34] [Server thread/ERROR]: [SimpleAdminHacks] Unhandled exception occured in onPacketSending(PacketEvent) for SimpleAdminHacks
java.lang.RuntimeException: Unable to clone object PacketContainer[type=ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[private final int net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata.a, private final java.util.List net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata.b]]] (com.comphenix.protocol.events.PacketContainer)
	at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:44) ~[ProtocolLib-4.8.0.jar:?]
	at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:256) ~[ProtocolLib-4.8.0.jar:?]
	at com.programmerdan.minecraft.simpleadminhacks.hacks.basic.AttrHider$3.onPacketSending(AttrHider.java:146) ~[SimpleAdminHacks-paper-2.0.0-SNAPSHOT.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib-4.8.0.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib-4.8.0.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib-4.8.0.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib-4.8.0.jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib-4.8.0.jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib-4.8.0.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[ProtocolLib-4.8.0.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[ProtocolLib-4.8.0.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[ProtocolLib-4.8.0.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[ProtocolLib-4.8.0.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib-4.8.0.jar:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib-4.8.0.jar:?]
	at net.minecraft.network.Connection.writePacket(Connection.java:433) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:382) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2040) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2026) ~[?:?]
	at net.minecraft.server.level.ChunkMap$TrackedEntity.broadcast(ChunkMap.java:2293) ~[?:?]
	at net.minecraft.server.level.ServerEntity.broadcastAndSend(ServerEntity.java:411) ~[?:?]
	at net.minecraft.server.level.ServerEntity.sendDirtyEntityData(ServerEntity.java:374) ~[?:?]
	at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:207) ~[?:?]
	at net.minecraft.server.level.ChunkMap.processTrackQueue(ChunkMap.java:2053) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:2064) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1076) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:907) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:629) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1593) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 1000, banned: 0], return=Exact class net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata, params=[{Type: Exact class net.minecraft.network.PacketDataSerializer, Index: 0}], paramCount=1}
	at com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174) ~[ProtocolLib-4.8.0.jar:?]
	at com.comphenix.protocol.events.PacketContainer.readObject(PacketContainer.java:330) ~[ProtocolLib-4.8.0.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor96.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at java.io.ObjectStreamClass.invokeReadObject(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readObject(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readObject(Unknown Source) ~[?:?]
	at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:42) ~[ProtocolLib-4.8.0.jar:?]
	... 33 more

**Comment by okx-code** [comment]
I'm closing this out as something that we won't fix. It could be revisited in the future, but it's not within our capacity to work on right now.
